services:
  - type: web
    name: vimal-portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ADMIN_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
